services:
  service-discovery:
    build:
      context: ./service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"
    networks:
      - santa_net

  msa:
    build:
      context: ./MsA
    container_name: msa
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: msa
      SPRING_DATASOURCE_URL: jdbc:postgresql://172.20.68.92:5432/santa_fe_db
      SPRING_DATASOURCE_USERNAME: santa_fe_admin
      SPRING_DATASOURCE_PASSWORD: santa_fe
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "true"
      EUREKA_CLIENT_FETCH_REGISTRY: "true"
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-discovery:8761/eureka/
    depends_on:
      - service-discovery
    networks:
      - santa_net

networks:
  santa_net:
    driver: bridge

